### ISSUE TITLE
missing php_oledb.dll

### ISSUE THREAD

**Issue by titu00** [chung-leong/pdo-oledb#1]
I can't find php_oledb.dll file. Could you provide a compiled version for win xp? I would like to connect to a DBASE file from pdo.

Thanks

**Comment by chung-leong** [comment]
What version of PHP are you using?
Date: Wed, 18 Dec 2013 18:39:22 -0800

**Comment by titu00** [comment]
php 5.3

Thanks

**Comment by chung-leong** [comment]
TS means thread-safe and NTS means non-thread-safe

https://dl.dropboxusercontent.com/u/80776822/pdo-oledb/php-5.3/php_pdo_oledb_ts.zip
https://dl.dropboxusercontent.com/u/80776822/pdo-oledb/php-5.3/php_pdo_oledb_nts.zip

https://dl.dropboxusercontent.com/u/80776822/pdo-oledb/php-5.4/php_pdo_oledb_ts.zip
https://dl.dropboxusercontent.com/u/80776822/pdo-oledb/php-5.4/php_pdo_oledb_nts.zip

https://dl.dropboxusercontent.com/u/80776822/pdo-oledb/php-5.5/php_pdo_oledb_ts.zip
https://dl.dropboxusercontent.com/u/80776822/pdo-oledb/php-5.5/php_pdo_oledb_nts.zip
